import {maxUpgrade} from '../src/upgrades.mjs';
import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import pg from '../../Server/node_modules/pg/lib/index.js';import {register} from '../../Server/src/services/accounts.mjs';import {browserOptions,webOrigin,apiOrigin,databaseUrl} from './environment.mjs';
const pool=new pg.Pool({connectionString:databaseUrl}),browser=await chromium.launch(browserOptions),ctx=await browser.newContext({viewport:{width:411,height:850},reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];
p.on('pageerror',e=>errors.push(e.message));const ready=()=>p.waitForFunction(()=>document.querySelector('#app').dataset.busy!=='true');const click=async s=>{await ready();await p.locator(s).first().click();await ready();};
let id;const profile=async()=>JSON.parse(JSON.stringify((await pool.query('SELECT data FROM vaults WHERE profile_id=$1',[id])).rows[0].data));
try{
 await p.goto(webOrigin);await p.locator('#next-dialog input').fill('CosmeticsProof');await click('#next-dialog button.primary');await p.locator('[data-nav="modes"]').waitFor();id=await p.evaluate(async()=>(await(await fetch('/api/web/v3/account/sessions')).json()).activeId);
 const d=await profile();d.balanceCents=100000000;d.xp=100000;d.tutorialDone=true;d.inventory.teleport=100;await pool.query('UPDATE vaults SET data=$2,balance_cents=$3 WHERE profile_id=$1',[id,d,d.balanceCents]);await p.reload();await p.locator('[data-nav="modes"]').waitFor();
 await click('[data-nav="shop"]');await click('[data-shop-tab="skins"]');await click('[data-skin-symbol="teleport"]');await click('[data-equip-skin="neon"]');assert((await profile()).ownedSkins.teleport.includes('neon'));assert.equal((await profile()).skins.teleport,'neon');
 await click('[data-equip-skin="classic"]');assert.equal((await profile()).skins.teleport,'classic');await click('[data-equip-skin="neon"]');
 await click('[data-shop-tab="goods"]');await click('#buy-avatar-bundle');assert((await profile()).ownedAvatars.includes('thunderlion'));
 await click('[data-nav="home"]');await click('[data-profile]');await click('[data-avatar]');await click('[data-avatar-id="eagle"]');assert.equal((await profile()).avatar,'eagle');await click('#choose-frame');await click('[data-frame="1"]');assert.equal((await profile()).frame,1);await click('#next-dialog [data-close]');
 await click('[data-nav="upgrades"]');await click('[data-upgrade="king"]');assert.equal((await profile()).upgrades.king,1);const expected=1+maxUpgrade(await profile(),'king').count;await click('[data-upgrade-max="king"]');assert.equal((await profile()).upgrades.king,expected);await p.screenshot({path:'artifacts/browser-upgrade-max.png'});
 await click('[data-nav="home"]');await click('[data-nav="inventory"]');await click('[data-item="teleport"]');await click('#sell-item');await click('#add-sale-skin');await p.locator('#sale-skin').selectOption('neon');await p.locator('[name="price"]').fill('4.25');await click('#sell-form button.primary');const lot=(await pool.query("SELECT id,skin,price_cents FROM listings WHERE seller=$1 AND status='open'",[id])).rows[0];assert.equal(lot.skin,'neon');assert.equal(lot.price_cents,'11225');assert(!(await profile()).ownedSkins.teleport.includes('neon'));
 await click('[data-nav="home"]');await click('[data-nav="market"]');await click('[data-market-symbol="teleport"]');await click('[data-cancel-listing="'+lot.id+'"]');await p.waitForTimeout(150);assert.equal((await pool.query('SELECT status FROM listings WHERE id=$1',[lot.id])).rows[0].status,'cancelled');assert((await profile()).ownedSkins.teleport.includes('neon'));
 const seller=await register(pool,'SafetySeller');await pool.query("UPDATE vaults SET data=jsonb_set(data,'{inventory,teleport}','100') WHERE profile_id=$1",[seller.id]);const r=await fetch(apiOrigin+'/api/v3/commands/sell',{method:'POST',headers:{Authorization:'Bearer '+seller.token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({symbol:'teleport',skin:'classic',quantity:70,price:'9.00'})});assert.equal(r.status,200);
 await click('#refresh-market');const before=await p.locator('.offer-row').count();await click('#more-market');assert((await p.locator('.offer-row').count())>before);await click('#sort-price');await p.screenshot({path:'artifacts/browser-market-pagination.png'});
 await click('#market-back');await click('[data-nav="home"]');await click('[data-profile]');await click('#safety');await p.locator('#target').fill(seller.id);await click('#block-player');assert.equal((await pool.query('SELECT 1 FROM blocks WHERE owner=$1 AND target=$2',[id,seller.id])).rowCount,1);await p.screenshot({path:'artifacts/browser-moderation.png'});
 await p.locator('#target').fill(seller.id);await p.locator('#reason').fill('Synthetic moderation test');await click('#next-dialog form button.primary');assert.equal((await pool.query('SELECT 1 FROM reports WHERE owner=$1 AND target=$2',[id,seller.id])).rowCount,1);
 await click('[data-profile]');await click('#safety');await click('[data-unblock="'+seller.id+'"]');assert.equal((await pool.query('SELECT 1 FROM blocks WHERE owner=$1 AND target=$2',[id,seller.id])).rowCount,0);
 assert.deepEqual(errors,[]);const report={passed:true,checks:['buy/equip skin','buy/equip avatar','frame','upgrade one/maximum affordable','sell with skin server surcharge','cancel returns skin','market filter sort pagination','report/block/unblock DB rows'],errors};await fs.writeFile('artifacts/cosmetics-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){await p.screenshot({path:'artifacts/cosmetics-failure.png'});console.error((await p.locator('body').innerText()).slice(-1200));throw e;}finally{await ctx.close();await browser.close();await pool.end();}
