import {chromium} from 'playwright';
import {browserOptions,webOrigin,apiOrigin,databaseUrl} from './environment.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createPool,transaction,one} from '../../Server/src/repositories/db.mjs';
import {register} from '../../Server/src/services/accounts.mjs';
import {tick} from '../../Server/src/services/game.mjs';
import {PRICES} from '../../Server/src/domain/economy.mjs';

const out=new URL('../artifacts/transition/gameplay/',import.meta.url);await fs.mkdir(out,{recursive:true});
const pool=createPool({databaseUrl}),browser=await chromium.launch(browserOptions),context=await browser.newContext({viewport:{width:411,height:780},reducedMotion:'reduce'}),page=await context.newPage();
const errors=[],checks=[],peers=[];let id;
page.on('pageerror',e=>errors.push(e.message));
const screenshot=async name=>{await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true});return name+'.png';};
const ready=()=>page.waitForFunction(()=>document.querySelector('#app')?.dataset.busy!=='true');
const click=async selector=>{await ready();await page.locator(selector).first().click();};
const cell=(side,index)=>`[data-side="${side}"][data-index="${index}"]`;
const symbol=(side,index,type)=>page.locator(cell(side,index)+`[data-symbol="${type}"]`).waitFor();
async function snap(){return page.evaluate(async id=>{const r=await fetch('/api/web/v3/bootstrap',{headers:{'X-Symbols-Account':id}});if(!r.ok)throw Error('Snapshot HTTP '+r.status);return r.json();},id);}
async function native(u,path,body){const r=await fetch(apiOrigin+'/api/v3/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+u.token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();assert.ok(r.ok,`${path}: ${r.status} ${JSON.stringify(data)}`);return data;}
async function peer(name){const u=await register(pool,name);const v=await one(pool,'SELECT data FROM vaults WHERE profile_id=$1',[u.id]);v.data.tutorialDone=true;await pool.query('UPDATE vaults SET data=$2 WHERE profile_id=$1',[u.id,v.data]);peers.push(u);return u;}
async function peerAct(u,action){const s=await native(u,'bootstrap');return native(u,'commands/action',{matchId:s.match.id,revision:s.match.revision,action});}
async function leave(){await click('#leave-game');await click('#confirm-leave');await page.locator('[data-nav="modes"]').waitFor();}
async function start(mode,size='small'){await click('[data-nav="modes"]');await page.locator('#board-size').selectOption(size);await click(`[data-start="${mode}"]`);}
async function setupLocal(index=65){await page.locator(cell(0,index)).waitFor();await click(cell(0,index));await symbol(0,index,'king');await click(cell(1,index));await symbol(1,index,'king');}
async function place(type,side,index,dir){await click(`[data-piece="${type}"]`);await click(cell(side,index));if(dir!==undefined)await click(`[data-direction="${dir}"]`);await symbol(side,index,type);await ready();}
async function botTurn(){const s=await snap();await transaction(pool,async c=>{const r=await one(c,'SELECT * FROM arenas WHERE id=$1 FOR UPDATE',[s.match.id]);if(r.data.players[r.data.actor].bot)await tick(c,r,Math.max(Date.now(),r.data.turnAt+600));});}
try{
 await page.goto(webOrigin);await page.locator('#next-dialog input').fill('Gameplay '+Date.now().toString().slice(-6));await click('#next-dialog button.primary');await page.locator('[data-nav="modes"]').waitFor();
 id=await page.evaluate(async()=>(await (await fetch('/api/web/v3/account/sessions')).json()).activeId);assert.ok(id);
 // Only synthetic resources are seeded. Main-player commands below always use UI.
 const v=await one(pool,'SELECT data FROM vaults WHERE profile_id=$1',[id]);v.data.balanceCents=1000000;v.data.balance=10000;v.data.inventory=Object.fromEntries(Object.keys(PRICES).map(k=>[k,100]));await pool.query('UPDATE vaults SET data=$2,balance_cents=$3 WHERE profile_id=$1',[id,v.data,v.data.balanceCents]);await page.reload();await page.locator('[data-nav="modes"]').waitFor();

 await start('play');await page.locator('.coach-panel').waitFor();let s=await snap();assert.equal(s.match.tutorial,true);assert.equal(s.match.advice.move.type,'king');assert.ok((await page.locator('.coach-panel').innerText()).includes('Первая партия'));await click('#coach-select');await page.locator('.coach-target').waitFor();const advised=s.match.advice.move.index;await click(cell(0,advised));await symbol(0,advised,'king');
 s=await snap();if(s.match.status==='setup')await botTurn();await page.locator('[data-piece="smile"]:enabled').waitFor();s=await snap();assert.equal(s.match.status,'play');assert.ok(s.match.advice?.text);checks.push({scenario:'play/tutorial: real king click, server hint highlight, playable bot match',status:'PASS',screenshot:await screenshot('tutorial')});await leave();

 await start('duel');await page.locator('.queue-page').waitFor();const duelist=await peer('Duel peer');await native(duelist,'commands/start',{mode:'duel',small:true});await page.locator(cell(0,65)).waitFor();await click(cell(0,65));await symbol(0,65,'king');await peerAct(duelist,{type:'king',index:65});await symbol(1,65,'king');await place('smile',0,4);await peerAct(duelist,{type:'smile',index:5});await symbol(1,5,'smile');s=await snap();assert.equal(s.match.players.length,2);assert.ok(s.match.players.every(p=>!p.bot));assert.equal(s.match.board.boards[1][5].type,'smile');checks.push({scenario:'human duel: UI king/move and peer event displayed',status:'PASS',screenshot:await screenshot('duel-peer')});await leave();

 await start('trial');await page.locator('.trial-clock').waitFor();await click(cell(0,65));await symbol(0,65,'king');s=await snap();if(s.match.status==='setup')await botTurn();await page.locator('[data-piece="smile"]:enabled').waitFor();await place('smile',0,2);s=await snap();assert.equal(s.match.mode,'trial');assert.equal(s.match.board.boards[0][2].type,'smile');checks.push({scenario:'trial: UI start, king, move and trial label',status:'PASS',screenshot:await screenshot('trial')});await leave();

 await start('local','large');await setupLocal(275);assert.equal(await page.locator('.unified-board [data-index]').count(),560);s=await snap();assert.deepEqual(s.match.size,[28,20]);assert.equal(s.match.board.boards[0][275].type,'king');assert.equal(s.match.board.boards[1][275].type,'king');await place('smile',0,3);checks.push({scenario:'large local 28x20: 560 rendered cells, both kings, real move',status:'PASS',screenshot:await screenshot('large-board')});await leave();

 await start('local');await setupLocal();const directions=[];
 for(let dir=0;dir<8;dir++){await place('point',0,14+dir,dir);s=await snap();assert.equal(s.match.board.boards[0][14+dir].dir,dir);const r=await one(pool,'SELECT data FROM arenas WHERE id=$1',[s.match.id]);assert.equal(r.data.g.boards[0][14+dir].dir,dir);directions.push(dir);await place('smile',1,dir);}
 await click('[data-piece="erase"]');await click(cell(0,14));await symbol(0,14,'empty');s=await snap();assert.equal(s.match.board.boards[0][14],null);assert.equal(s.match.actor,0);const beforeAngry=s.profile.inventory.angry;await click('[data-piece="angry"]');await page.locator('[data-piece="smile"]:enabled').waitFor();s=await snap();assert.equal(s.match.board.extra,2);assert.equal(s.profile.inventory.angry,beforeAngry-1);await place('smile',0,25);s=await snap();assert.equal(s.match.actor,0);assert.equal(s.match.board.extra,1);await place('smile',0,26);s=await snap();assert.equal(s.match.actor,1);assert.equal(s.match.board.extra,0);checks.push({scenario:'eight direction dialog buttons; erase free turn; angry two consecutive UI moves',status:'PASS',directions,screenshot:await screenshot('directions-erase-angry')});await leave();

 await click('[data-nav="modes"]');await page.locator('#board-size').selectOption('small');await click('[data-room]');
 const createButton=page.getByRole('button',{name:'Создать комнату',exact:true});await createButton.click();await page.locator('.room-code').waitFor();s=await snap();const roomPeer=await peer('Room peer');await native(roomPeer,'commands/start',{mode:'room',code:s.match.code});await page.locator(cell(0,65)).waitFor();await click(cell(0,65));await symbol(0,65,'king');await peerAct(roomPeer,{type:'king',index:56});await symbol(1,56,'king');
 // Controlled endgame: main user still places the actual tank via shelf/cell/
 // direction UI, then the other human's API response resolves the pending shot.
 s=await snap();const row=await one(pool,'SELECT data FROM arenas WHERE id=$1',[s.match.id]);for(const index of [0,14,28])row.data.g.boards[1][index]={type:'smile',seat:1};row.data.started=Date.now()-10000;await pool.query('UPDATE arenas SET data=$2 WHERE id=$1',[s.match.id,row.data]);await page.reload();await symbol(1,0,'smile');const before=await snap();await place('tank',0,14,0);await peerAct(roomPeer,{type:'smile',index:2});await page.locator('.battle-result').waitFor();await ready();s=await snap();assert.equal(s.match.status,'done');assert.equal(s.match.result.won,true);assert.equal(s.profile.xp,before.profile.xp+1200);assert.equal(BigInt(s.profile.balanceCents),BigInt(before.profile.balanceCents)+300n);assert.equal(s.profile.quests.clean,before.profile.quests.clean+1);assert.equal(s.profile.quests.blocks,before.profile.quests.blocks+1);assert.match(await page.locator('.battle-result').innerText(),/Победа![\s\S]*1200 очков[\s\S]*3 рубинов/);const persisted=await one(pool,'SELECT data,balance_cents FROM vaults WHERE profile_id=$1',[id]);assert.equal(persisted.balance_cents,s.profile.balanceCents);assert.equal(persisted.data.history[0].id,s.match.id);checks.push({scenario:'human room: UI tank attack, peer reply, victory/rewards exactly match DB',status:'PASS',screenshot:await screenshot('room-victory')});
 await click('[data-nav="home"]');await click('[data-profile]');await page.locator('.match-history').waitFor();const first=page.locator('.match-history li').first();assert.match(await first.innerText(),/Победа[\s\S]*Room peer[\s\S]*1200 очков/);checks.push({scenario:'profile displays finished-match history and XP',status:'PASS',screenshot:await screenshot('history')});await click('#next-dialog [data-close]');await click('[data-nav="quests"]');const quests=await page.locator('.quest-list').innerText();assert.equal((quests.match(/Выполнено: 1/g)??[]).length,2);checks.push({scenario:'quests screen displays both server-awarded counters',status:'PASS',screenshot:await screenshot('quests')});
 assert.deepEqual(errors,[]);const storage=await page.evaluate(()=>({local:Object.fromEntries(Object.entries(localStorage)),session:Object.fromEntries(Object.entries(sessionStorage)),cookie:document.cookie}));assert.ok(!/"(?:token|authorization)"\s*:/i.test(JSON.stringify(storage)));assert.ok(!storage.cookie.includes('__Host-symbols-browser'));
 const report={passed:true,scope:'Real main-account UI clicks; peer HTTP commands; controlled local endgame fixture; no production',checks,errors};await fs.writeFile(new URL('report.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){await screenshot('failure');await fs.writeFile(new URL('report.json',out),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));console.error(e);console.error((await page.locator('body').innerText()).slice(-2400));process.exitCode=1;}
finally{await context.close();await browser.close();await pool.end();}
