import test from 'node:test';import assert from 'node:assert/strict';import {Client} from '../src/client.mjs';
const snap={cursor:'0',revision:'0',profile:{balanceCents:'100',inventory:{}},match:null};
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:(...a)=>resolve(...a)};};
function fixture(transport){const map=new Map(),c=new Client({transport,storage:{getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)}});c.session={id:'test',token:'fake'};c.state=structuredClone(snap);return {c,map};}
test('native polling is strictly single-flight over repeated lifecycle and account changes',async()=>{let live=0,peak=0,total=0;const requests=[];const {c}=fixture(async path=>{if(path==='bootstrap')return {status:200,data:snap};live++;peak=Math.max(peak,live);total++;const d=deferred();requests.push(d);await d.promise;live--;return {status:200,data:{events:[],cursor:'0'}};});c.start();await new Promise(r=>setImmediate(r));for(let i=0;i<30;i++){c.setActive(false);c.setActive(true);}assert.equal(total,1);requests[0].resolve();await new Promise(r=>setImmediate(r));assert.equal(total,2);assert.equal(peak,1);c.stop();requests[1].resolve();await c.worker;});
test('429 preserves receipt key and honors Retry-After; 409 clears rejected command',async()=>{let status=429;const {c}=fixture(async()=>({status,data:{error:{message:'retry',code:status===429?'RATE_LIMIT':'CONFLICT'}},headers:{'retry-after':'20'}}));await assert.rejects(c.command('buy',{id:'lot'}),e=>e.status===429);const key=c.pending.key;await assert.rejects(c.reconcile(),/Подожди/);assert.equal(c.pending.key,key);c.retryAt=0;status=409;await assert.rejects(c.reconcile(),e=>e.status===409);assert.equal(c.pending,null);});
test('401 stops subscription and calls recovery UI without restarting worker',async()=>{let revoked=0;const {c}=fixture(async()=>({status:401,data:{error:{message:'expired',code:'UNAUTHORIZED'}}}));c.onUnauthorized=()=>revoked++;c.start();await c.worker;assert.equal(revoked,1);assert.equal(c.running,false);assert.equal(c.state,null);});
test('purchase retries reject malformed timestamps and clock rollback',async()=>{const {c}=fixture(async()=>{throw Error('must not send');});for(const at of [null,'yesterday',Date.now()+10000,Date.now()-25*3600000]){await c.savePending({kind:'buy',body:{id:'lot'},key:'same-key',at});await assert.rejects(c.reconcile(),/Старая операция/);}});
test('5xx preserves unknown outcome and same key for later deliberate retry',async()=>{let fail=true;const keys=[];const {c}=fixture(async(path,a)=>{if(path==='bootstrap')return {status:200,data:snap};keys.push(a.key);if(fail){fail=false;return {status:503,data:{error:{message:'unavailable'}}};}return {status:200,data:{ok:true}};});await assert.rejects(c.command('buy',{id:'lot'}));await c.reconcile();assert.equal(keys.length,2);assert.equal(keys[0],keys[1]);});
test('own logout/delete stops poll before mutation; stale poll 401 cannot invalidate successful terminal result',async()=>{for(const kind of ['logout','delete-account']){const poll=deferred(),posted=deferred();let unauthorized=0,terminated=0;const {c}=fixture(async(path)=>{if(path.startsWith('changes?'))return poll.promise;if(path.startsWith('commands/')){posted.resolve();return {status:200,data:{ok:true}};}return {status:200,data:snap};});c.onUnauthorized=()=>{unauthorized++;c.useSession(null);};c.onTerminal=async()=>{terminated++;await c.useSession(null);};c.start();await new Promise(r=>setImmediate(r));const command=c.command(kind,kind==='delete-account'?{confirm:true}:{});await posted.promise;poll.resolve({status:401,data:{error:{code:'UNAUTHORIZED',message:'revoked'}}});await command;await c.worker;assert.equal(unauthorized,0);assert.equal(terminated,1);assert.equal(c.session,null);assert.equal(c.running,false);}});
