import test from 'node:test';
import assert from 'node:assert/strict';
import {reduceEvents} from '../src/state.mjs';
import {Client} from '../src/client.mjs';
const initial=()=>({cursor:'9007199254740993',revision:'1',profile:{nick:'Test',balanceCents:'100'},match:{id:'m',revision:'4',board:{boards:[[null,null],[null,null]],hp:[100,100]}}});
const event=()=>({cursor:'9007199254740994',revision:'2',serverTime:'2026-10-08T00:00:00Z',entityId:'m',profilePatch:{balanceCents:'200'},match:{baseRevision:'4',patch:{revision:'5',board:{cells:[{side:0,index:1,value:{type:'king'}}],hp:[110,100]}}}});
test('decimal cursors retain BIGINT precision, cell deltas preserve untouched cells',()=>{const before=initial(),after=reduceEvents(before,{events:[event()],cursor:'9007199254740994'});assert.equal(after.cursor,'9007199254740994');assert.equal(after.match.board.boards[0][1].type,'king');assert.equal(before.match.board.boards[0][1],null);assert.equal(after.profile.balanceCents,'200');});
test('duplicate delivery is harmless',()=>{const page={events:[event()],cursor:'9007199254740994'};const next=reduceEvents(initial(),page);assert.deepEqual(reduceEvents(next,page),next);});
test('cursor gap and wrong match revision require snapshot, never partially applied',()=>{for(const corrupt of [e=>e.cursor='9007199254740995',e=>e.match.baseRevision='3']){const before=initial(),e=event();corrupt(e);assert.throws(()=>reduceEvents(before,{events:[e],cursor:e.cursor}),/SNAPSHOT_REQUIRED/);assert.equal(before.profile.balanceCents,'100');}});
function fixture(){const data=new Map(),calls=[];let lose=false;const receipts=new Map();const state={...initial(),cursor:'0',match:{id:'m',revision:'4',board:null,uses:{},effects:[]}};const client=new Client({storage:{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},transport:async(path,args)=>{calls.push({path,...args});if(path==='bootstrap')return {status:200,data:structuredClone(state)};const result=receipts.get(args.key)??{commandId:args.key};receipts.set(args.key,result);if(lose){lose=false;throw Error('lost response');}return {status:200,data:result};}});client.session={id:'a',token:'synthetic-token'};client.state=state;return {client,calls,receipts,lose:()=>lose=true};}
test('lost purchase response blocks new operation and retry uses the original key',async()=>{const f=fixture();f.lose();await assert.rejects(f.client.command('buy',{id:'lot'}));const key=f.client.pending.key;await assert.rejects(f.client.command('buy',{id:'another'}),/Сначала/);await f.client.reconcile();assert.equal(f.receipts.size,1);assert.equal(f.calls.filter(c=>c.key).at(-1).key,key);assert.equal(f.client.pending,null);});
test('lost move is reconciled with snapshot, never replayed',async()=>{const f=fixture();f.lose();await assert.rejects(f.client.command('action',{action:{type:'king',index:1}}));await f.client.reconcile();assert.equal(f.calls.filter(c=>c.path==='commands/action').length,1);assert.equal(f.client.pending,null);});
test('write-ahead storage failure prevents sending command',async()=>{const f=fixture();f.client.flush=async()=>{throw Error('disk full');};await assert.rejects(f.client.command('buy',{id:'lot'}),/disk full/);assert.equal(f.calls.length,0);});
test('concurrent taps cannot produce two commands',async()=>{const f=fixture();const first=f.client.command('buy',{id:'lot'});await assert.rejects(f.client.command('buy',{id:'lot'}),/Дождись/);await first;assert.equal(f.calls.filter(c=>c.key).length,1);});
test('stale snapshot from a previous account is ignored',async()=>{const f=fixture();let finish;f.client.transport=()=>new Promise(r=>finish=r);const request=f.client.bootstrap();await f.client.useSession({id:'b',token:'other'});finish({status:200,data:initial()});await request;assert.equal(f.client.state,null);});
