from pathlib import Path
p=Path('Client/artifacts/ui-parity');scenes=['home','modes','setup','board','selected','direction','inventory','item','upgrades','shop','market','profile','quests','rules','large','large-zoom','result','owned-inventory','case','skins','frames','avatars','waiting','teleport-source','teleport-direction','teleport-done','offline','reconnected','narrow-home','narrow-inventory','font130-home','font130-inventory','play-board','team-waiting','team-board','team-result','upgrades-after']
html='''<!doctype html><meta charset="utf-8"><title>Символы · Web / Android</title><style>body{background:#15141b;color:#eee;font:16px system-ui;margin:24px}h1{font-size:28px}section{margin:32px 0;border-top:1px solid #555}main{display:flex;gap:20px;overflow:auto}figure{margin:0;flex:0 0 411px}figcaption{padding:10px}.shot{height:660px;overflow:hidden;background:#222}.shot img{width:411px;display:block}.android img{transform:translateY(-24px)}.missing{padding:24px;color:#ebaf8e}</style><h1>Web-эталон → Android UI</h1><p>Результат: основной UI и управление восстановлены; это не pixel-identical приёмка всех сцен. Рамки используют CSS-палитры/стопы металлических градиентов; сложный conic/shine — native приближение; косметика открывается отдельными экранами, часть web — modal. Улучшения доступны inline без дополнительного modal. Эффекты перенесены, но синхронное покадровое сравнение не проведено. Ordinary/team UI smoke с реальными API peers прошёл, все seats походили. Waiting/result сняты парой. Шрифты и emoji платформенные; синтетические аккаунты различаются историей и XP. Network и teleport проверены SQL-asserts, не только картинками.</p><p>Web: original next.mjs8c95399, local Worker+SQLite. Android: real devQa/R8 screenshots, Serverv3 local test PostgreSQL. Web viewport411×660 CSSpx; Android36 content1080×1731px at420dpi (~411×660dp), system bars visually cropped here only. Full original PNG remain beside this report. Avatar emoji/font differ by platform.</p>'''
for scene in scenes:
 html+=f'<section><h2>{scene}</h2><main>'
 for title,file,android in [('Web',f'web-{scene}.png',False),('Android before',f'../screenshots/devQa-emulator-5556-{dict(board="match",setup="match").get(scene,scene)}.png',True),('Android current',f'android-emulator-5556-{scene}.png',True)]:
  html+=f'<figure><figcaption>{title}</figcaption>'
  if (p/file).exists():html+=f'<div class="shot {"android" if android else ""}"><img src="{file}"></div>'
  else:html+=f'<div class="missing">{"Исторический before не снимался" if title == "Android before" else "Нет сопоставимого кадра; см. матрицу ограничений"}</div>'
  html+='</figure>'
 html+='</main></section>'
(p/'index.html').write_text(html,encoding='utf8')
