import assert from 'node:assert/strict';import fs from 'node:fs';import {parseHTML} from 'linkedom';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {freshProgress} from '../dist/economy.mjs';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Q{constructor(s){this.s=s;this.args=[];}bind(...a){this.args=a;return this;}async first(){return sql.prepare(this.s).get(...this.args)??null;}async all(){return{results:sql.prepare(this.s).all(...this.args)};}async run(){return{meta:sql.prepare(this.s).run(...this.args)};}}
const DB={prepare:s=>new Q(s),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const p=freshProgress();p.nick='Инвентарь';p.human.unlocked.push('sword');
const {document,window}=parseHTML(fs.readFileSync('dist/index.html','utf8'));globalThis.document=document;globalThis.window=window;const create=document.createElement.bind(document);document.createElement=(tag,...args)=>{const el=create(tag,...args);if(tag==='dialog'){el.showModal=()=>el.open=true;el.close=()=>el.open=false;}return el;};
const registration=await worker.fetch(new Request('https://game.test/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nick:p.nick})}),{DB});const registered=await registration.json();sql.prepare('UPDATE profiles SET data=? WHERE id=?').run(JSON.stringify(p),registered.id);const values=new Map([['symbols-progress-v1',JSON.stringify(p)],['symbols-session',JSON.stringify({id:registered.id,token:registered.token})]]);globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};globalThis.setInterval=()=>0;globalThis.fetch=async(url,opts)=>worker.fetch(new Request('https://game.test'+url,{...opts,headers:{...opts.headers,Origin:'https://game.test'}}),{DB});const pause=()=>new Promise(r=>setTimeout(r,5));

await import('../dist/next.mjs');await pause();document.querySelector('[data-nav="shop"]').click();await pause();assert.equal(document.querySelectorAll('[data-case]').length,4);document.querySelector('[data-case="assault"]').click();assert.equal(document.querySelectorAll('.case-odds>div').length,5);assert.ok(document.querySelector('#open-case').disabled);assert.ok(document.querySelector('#buy-case').disabled);document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-profile]').click();document.querySelector('#choose-frame').click();assert.equal(document.querySelectorAll('[data-frame]').length,30);assert.ok(document.querySelector('[data-frame="1"]').disabled);document.querySelector('#hide-frame').click();await pause();assert.match(document.querySelector('#hide-frame').textContent,/скрыта/);document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-promo]').click();document.querySelector('#next-dialog input').value='BOSS4229';document.querySelector('#next-dialog form').onsubmit({preventDefault(){}});await pause();document.querySelector('[data-nav="shop"]').click();await pause();document.querySelector('[data-case="assault"]').click();document.querySelector('#buy-case').click();document.querySelector('#buy-case').click();await pause();await pause();assert.equal(document.querySelector('#case-owned').textContent,'2');assert.ok(!document.querySelector('#open-case').disabled);document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-nav="inventory"]').click();await pause();assert.equal(document.querySelector('[data-case="assault"] .inventory-count').textContent,'×2');document.querySelector('[data-case="assault"]').click();document.querySelector('#open-case').click();await pause();assert.match(document.querySelector('#case-result').textContent,/Добавлен в инвентарь/);assert.equal(document.querySelectorAll('.reel-item').length,40);document.querySelector('#case-inventory').click();assert.ok(document.querySelector('.inventory-grid'));assert.equal(document.querySelector('[data-case="assault"] .inventory-count').textContent,'×1');console.log('PASS shop navigation, odds, purchase/open flow, reward, inventory, and 24 frame choices.');
