import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {freshProgress,PRICES} from '../dist/economy.mjs';import {createGame,shot} from '../dist/engine.mjs';import {startArena,arenaAction} from '../server/arena-engine.mjs';import {levelInfo,trialResult} from '../dist/progression.mjs';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Query{constructor(s){this.s=s;this.args=[];}bind(...args){this.args=args;return this;}async first(){return sql.prepare(this.s).get(...this.args)??null;}async all(){return {results:sql.prepare(this.s).all(...this.args)};}async run(){return {meta:sql.prepare(this.s).run(...this.args)};}}
const DB={prepare:s=>new Query(s),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
let now=Date.now();Date.now=()=>now;
async function api(route,body={},user=null){const res=await worker.fetch(new Request('https://game.test/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://game.test',...(user?{Authorization:'Bearer '+user.token}:{})},body:JSON.stringify(body)}),{DB});const d=await res.json();if(!res.ok)throw Error(d.error);return d;}
async function user(n){const p=freshProgress();p.human.unlocked.push('circle');const u=await api('register',{nick:'Тест '+n,progress:p});sql.prepare('UPDATE profiles SET data=? WHERE id=?').run(JSON.stringify(p),u.id);await api('v2/profile',{},u);return u;}


const {FRAMES,unlockedFrames,activeFrame}=await import('../dist/frames.mjs');const {CASES,drawCase}=await import('../dist/cases.mjs');const {SYMBOL_RARITY}=await import('../dist/rarity.mjs');
assert.equal(FRAMES.length,30);assert.equal(FRAMES[3].level,40);assert.equal(FRAMES[4].name,'Серебро 1');assert.equal(FRAMES[23].level,240);
for(const lv of [1,9,10,20,40,50,80,240,300])assert.equal(unlockedFrames(THRESHOLDS_TEST(lv)),Math.min(30,Math.floor(lv/10)));
function THRESHOLDS_TEST(lv){let xp=[0,260,560,660,800,1000];while(xp.length<lv)xp.push(xp.at(-1)+(xp.length%2?150:100));return xp[lv-1];}
assert.equal(SYMBOL_RARITY.tank,'arcana');assert.equal(SYMBOL_RARITY.powerful,'arcana');assert.equal(SYMBOL_RARITY.laser,'legendary');assert.equal(SYMBOL_RARITY.inspect,'legendary');
const all=new Set();for(const c of CASES){assert.equal(c.drops.reduce((n,d)=>n+d[1],0),10000);assert.equal(c.drops.filter(([t])=>SYMBOL_RARITY[t]==='arcana').reduce((n,d)=>n+d[1],0),20);for(const [t] of c.drops)all.add(t);assert.equal(drawCase(c,0),c.drops[0][0]);assert.equal(drawCase(c,0.999999),c.drops.at(-1)[0]);}assert.deepEqual([...all].sort(),Object.keys(PRICES).sort());
const u=await user('Кейсы');await assert.rejects(()=>api('v2/frame',{frame:1},u),/не открыта/);await api('v2/promo',{code:'BOSS4229'},u);
const key=crypto.randomUUID();let r=await api('v2/buy-case',{case:'assault',key},u);assert.equal(r.profile.balanceCents,3100);assert.equal(r.profile.cases.assault,1);r=await api('v2/buy-case',{case:'assault',key},u);assert.equal(r.profile.balanceCents,3100);assert.equal(r.profile.cases.assault,1);
const before={...r.profile.inventory},openKey=crypto.randomUUID();r=await api('v2/open-case',{case:'assault',key:openKey},u);assert.equal(r.profile.cases.assault,0);assert.equal(r.profile.inventory[r.drop],(before[r.drop]??0)+1);const drop=r.drop;const again=await api('v2/open-case',{case:'assault',key:openKey},u);assert.equal(again.drop,drop);assert.deepEqual(again.profile.inventory,r.profile.inventory);await assert.rejects(()=>api('v2/open-case',{case:'assault',key:crypto.randomUUID()},u),/купи кейс/);
let d=JSON.parse(sql.prepare('SELECT data FROM vaults WHERE profile_id=?').get(u.id).data);d.xp=THRESHOLDS_TEST(50);sql.prepare('UPDATE vaults SET data=? WHERE profile_id=?').run(JSON.stringify(d),u.id);r=await api('v2/frame',{frame:5},u);assert.equal(activeFrame(r.profile),5);await assert.rejects(()=>api('v2/frame',{frame:6},u),/не открыта/);r=await api('v2/frame',{frame:null},u);assert.equal(activeFrame(r.profile),null);r=await api('v2/frame',{frame:1},u);assert.equal(activeFrame(r.profile),1);
console.log('PASS 24 frame gates, frame selection/hiding, all paid symbols in cases, 0.2% Arcana, exact case payment and replay-safe reward.');

const promoUser=await user('Большой промо');let promoResult=await api('v2/promo',{code:'10000b'},promoUser);assert.equal(promoResult.profile.balanceCents,1000100);await assert.rejects(()=>api('v2/promo',{code:'10000B'},promoUser),/использован/);promoResult=await api('v2/promo',{code:'Boss 4229'},promoUser);assert.equal(promoResult.profile.balanceCents,1005100);console.log('PASS 10000B awards exactly 10000 once, BOSS4229 still awards 50.');

const beforeRift=(await api('v2/profile',{},promoUser)).profile.balanceCents;const boughtRift=await api('v2/buy-case',{case:'rift',key:crypto.randomUUID()},promoUser);assert.equal(boughtRift.profile.balanceCents,beforeRift-7500);assert.equal(boughtRift.profile.cases.rift,1);console.log('PASS Rift costs 75 bucks.');
