import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {freshProgress,PRICES} from '../dist/economy.mjs';import {createGame,shot} from '../dist/engine.mjs';import {startArena,arenaAction} from '../server/arena-engine.mjs';import {levelInfo,trialResult} from '../dist/progression.mjs';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Query{constructor(s){this.s=s;this.args=[];}bind(...args){this.args=args;return this;}async first(){return sql.prepare(this.s).get(...this.args)??null;}async all(){return {results:sql.prepare(this.s).all(...this.args)};}async run(){return {meta:sql.prepare(this.s).run(...this.args)};}}
const DB={prepare:s=>new Query(s),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
let now=Date.now();Date.now=()=>now;
async function api(route,body={},user=null){const res=await worker.fetch(new Request('https://game.test/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://game.test',...(user?{Authorization:'Bearer '+user.token}:{})},body:JSON.stringify(body)}),{DB});const d=await res.json();if(!res.ok)throw Error(d.error);return d;}
async function user(n){const p=freshProgress();p.human.unlocked.push('circle');const u=await api('register',{nick:'Тест '+n,progress:p});sql.prepare('UPDATE profiles SET data=? WHERE id=?').run(JSON.stringify(p),u.id);await api('v2/profile',{},u);return u;}


const a=await user('Лимиты');let r=await api('v2/promo',{code:'Х2'},a);assert.equal(r.profile.inventory.arrowx2,10);for(const code of ['2X','X2','2Х'])await assert.rejects(()=>api('v2/promo',{code},a),/использован/);
for(const [symbol,count] of [['tank',5],['feedback',3],['sword',5]]){const s={size:[10,14],players:[{id:'a',bot:false,inventory:{[symbol]:1}},{id:'b',bot:false,inventory:{}}]};startArena(s,Date.now());arenaAction(s,{type:'king',index:56},0,Date.now());arenaAction(s,{type:'king',index:56},1,Date.now());let charged=0;for(let i=0;i<count;i++){const result=arenaAction(s,{type:symbol,index:14+i,dir:2},0,Date.now());if(result.consumed)charged++;arenaAction(s,{type:'smile',index:28+i},1,Date.now());}assert.equal(charged,1);assert.equal(s.g.playerStocks[0][symbol],0);assert.equal(s.players[0].inventory[symbol],0);assert.throws(()=>arenaAction(s,{type:symbol,index:40,dir:2},0,Date.now()));}
console.log('PASS one copy unlocks full tank/feedback/sword match limits and is consumed once; all X2 aliases share one redemption.');
