import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {freshProgress} from '../dist/economy.mjs';import {createGame,action,shot} from '../dist/engine.mjs';import {calculateRank,cleanNick} from '../dist/profile.mjs';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Query{constructor(s){this.s=s;this.args=[];}bind(...args){this.args=args;return this;}async first(){return sql.prepare(this.s).get(...this.args)??null;}async run(){return {meta:sql.prepare(this.s).run(...this.args)};}}
const DB={prepare:s=>new Query(s),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
async function api(route,body={},user=null){const res=await worker.fetch(new Request('https://game.test/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://game.test',...(user?{Authorization:'Bearer '+user.token}:{})},body:JSON.stringify(body)}),{DB});const data=await res.json();if(!res.ok)throw Error(data.error);return data;}
const a=await api('register',{nick:'ЛунныйТанк',progress:freshProgress()}),b=await api('register',{nick:'ЗвёздныйКот',progress:freshProgress()});assert.ok(a.token!==b.token);assert.equal((await api('poll',{},a)).online,2);
let r=await api('create',{size:[10,14]},a);assert.equal(r.match.status,'waiting');const code=r.match.code;r=await api('join',{code},b);assert.equal(r.match.status,'warmup');assert.equal(r.match.seat,1);assert.equal(r.match.state.g.boards[0].length,70);
let m=r.match;let actor=m.state.g.current===0?a:b;r=await api('action',{revision:m.revision,action:{type:'king',index:56}},actor);assert.equal(r.match.state.g.setup,1);const oldRevision=m.revision;r=await api('action',{revision:oldRevision,action:{type:'king',index:56}},b);assert.equal(r.match.state.g.setup,1);
let state=r.match.state;state.warmupEnd=Date.now()-10;sql.prepare('UPDATE matches SET state=? WHERE id=?').run(JSON.stringify(state),r.match.id);r=await api('poll',{},a);assert.equal(r.match.status,'play');assert.equal(r.match.state.g.setup,0);assert.equal(r.profile.human.balance,1);
await api('action',{revision:r.match.revision,action:{type:'king',index:56}},a);r=await api('poll',{},b);await api('action',{revision:r.match.revision,action:{type:'king',index:56}},b);r=await api('poll',{},a);const other=r.match.state.g.current===0?b:a;await assert.rejects(()=>api('action',{revision:r.match.revision,action:{type:'smile',index:0}},other),/ход соперника/);
sql.prepare('UPDATE profiles SET seen=? WHERE id=?').run(Date.now()-31000,b.id);r=await api('poll',{},a);assert.equal(r.match.status,'done');assert.equal(r.match.state.g.winner,0);assert.equal(r.profile.history[0].outcome,'win');assert.equal(r.profile.history[0].mode,'online');await api('leave',{},a);await api('leave',{},b);
r=await api('queue',{},a);r=await api('queue',{},b);assert.equal(r.match.status,'negotiate');await api('size',{size:[28,20]},a);r=await api('size',{size:[10,14]},b);assert.equal(r.match.state.round,1);await api('size',{size:[10,14]},a);r=await api('size',{size:[28,20]},b);assert.equal(r.match.status,'done');assert.equal(r.match.state.rematch,true);await api('leave',{},a);await api('leave',{},b);
// A second mismatch must not match the same pair immediately.
await api('queue',{},a);r=await api('queue',{},b);assert.equal(r.match.status,'waiting');await api('leave',{},a);await api('leave',{},b);
r=await api('create',{size:[28,20]},a);r=await api('join',{code:r.match.code},b);await api('nickname',{nick:'НовыйНик'},a);assert.equal((await api('poll',{},a)).nick,'НовыйНик');
for(const [type,n,target,destroy] of [['arrow',0,'point',true],['arrow',2,'inspect',false],['arrow',3,'inspect',true],['laser',0,'inspect',true],['arrow',4,'powerful',false],['arrow',5,'powerful',true],['laser',1,'powerful',false],['laser',2,'powerful',true],['tank',0,'powerful',true]]){const g=createGame(10,14);g.boards[0][24]={type,dir:0};for(let i=1;i<=n;i++)g.boards[0][24-i]={type:'point',dir:2};g.boards[1][24]={type:target,dir:2};g.boards[1][66]={type:'king'};const out=shot(g,{player:0,index:24},true);assert.equal(g.boards[1][24]===null,destroy,`${type},${n},${target}`);assert.equal(out.damage,type==='tank'?200:0);}
let g=createGame(10,14);g.setup=2;g.boards[0][56]={type:'king'};g.boards[1][56]={type:'king'};g.boards[0][15]={type:'arrow',dir:0,spent:true};g.current=0;const stock=g.stocks[0].teleport;action(g,{type:'teleport',source:15,index:20,dir:7});assert.equal(g.boards[0][15],null);assert.equal(g.boards[0][20].spent,false);assert.equal(g.boards[0][20].dir,7);assert.equal(g.pending[0].index,20);assert.equal(g.current,1);assert.equal(g.stocks[0].teleport,stock-1);
g.current=0;g.boards[0][57]={type:'point',dir:6,kingGranted:true};g.hp[0]=110;g.maxHp[0]=110;action(g,{type:'teleport',source:57,index:58,dir:6});assert.equal(g.hp[0],110);assert.equal(g.maxHp[0],110);
assert.equal(calculateRank(Array.from({length:5},()=>({won:true,damage:0}))).name,'Легенда');assert.equal(calculateRank(Array.from({length:5},()=>({won:false,damage:100}))).name,'Бронза I');assert.throws(()=>cleanNick('fuck'));assert.equal(cleanNick('ЗвёздныйКот'),'ЗвёздныйКот');
console.log('PASS: guest sessions, presence, room duel, warmup reset, turn security, revision replay, disconnect loss, size renegotiation, rematching, nicknames, teleport refresh, booster combat and ranks.');

const recoverUser=await api('register',{nick:'КодовыйКот',progress:freshProgress()});const recoveryProgress=freshProgress();recoveryProgress.nick='КодовыйКот';recoveryProgress.human.balance=777;recoveryProgress.redeemedPromos=['M4FX5267'];
const codeResult=await api('recovery-code',{nick:recoveryProgress.nick,progress:recoveryProgress},recoverUser);assert.match(codeResult.code,/^\d{9}$/);assert.equal((await api('recovery-code',{nick:recoveryProgress.nick,progress:recoveryProgress,code:codeResult.code},recoverUser)).code,codeResult.code);
await assert.rejects(()=>api('recover',{code:'000000000'}),/Код не найден/);const restored=await api('recover',{code:codeResult.code});assert.equal(restored.id,recoverUser.id);assert.equal(restored.profile.human.balance,777);assert.deepEqual(restored.profile.redeemedPromos,['M4FX5267']);await assert.rejects(()=>api('poll',{},recoverUser),/Сессия не найдена/);assert.equal((await api('poll',{},restored)).nick,'КодовыйКот');
for(let i=0;i<3;i++)await assert.rejects(()=>api('recover',{code:'000000000'}));await assert.rejects(()=>api('recover',{code:codeResult.code}),/Слишком много попыток/);console.log('PASS: recovery snapshot, stable code, token rotation, invalid code and rate limit');
