import assert from 'node:assert/strict';import fs from 'node:fs';import {parseHTML} from 'linkedom';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {freshProgress} from '../dist/economy.mjs';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Q{constructor(s){this.s=s;this.args=[];}bind(...a){this.args=a;return this;}async first(){return sql.prepare(this.s).get(...this.args)??null;}async all(){return{results:sql.prepare(this.s).all(...this.args)};}async run(){return{meta:sql.prepare(this.s).run(...this.args)};}}
const DB={prepare:s=>new Q(s),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const p=freshProgress();p.nick='Инвентарь';p.human.unlocked.push('sword');
const {document,window}=parseHTML(fs.readFileSync('dist/index.html','utf8'));globalThis.document=document;globalThis.window=window;const create=document.createElement.bind(document);document.createElement=(tag,...args)=>{const el=create(tag,...args);if(tag==='dialog'){el.showModal=()=>el.open=true;el.close=()=>el.open=false;}return el;};
const registration=await worker.fetch(new Request('https://game.test/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nick:p.nick})}),{DB});const registered=await registration.json();sql.prepare('UPDATE profiles SET data=? WHERE id=?').run(JSON.stringify(p),registered.id);const values=new Map([['symbols-progress-v1',JSON.stringify(p)],['symbols-session',JSON.stringify({id:registered.id,token:registered.token})]]);globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};globalThis.setInterval=()=>0;globalThis.fetch=async(url,opts)=>worker.fetch(new Request('https://game.test'+url,{...opts,headers:{...opts.headers,Origin:'https://game.test'}}),{DB});const pause=()=>new Promise(r=>setTimeout(r,5));

await import('../dist/next.mjs');await pause();document.querySelector('[data-promo]').click();assert.equal(document.querySelector('#next-dialog input').getAttribute('placeholder'),null);document.querySelector('#next-dialog input').value='10000B';document.querySelector('#next-dialog form').onsubmit({preventDefault(){}});await pause();document.querySelector('[data-profile]').click();document.querySelector('[data-avatar]').click();assert.equal(document.querySelectorAll('[data-avatar-id]').length,2);assert.equal(document.querySelector('#upload-avatar'),null);document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-nav="shop"]').click();await pause();assert.equal(document.querySelectorAll('[data-shop-tab]').length,3);document.querySelector('[data-shop-tab="goods"]').click();assert.match(document.body.textContent,/500 рубинов/);document.querySelector('#buy-avatar-bundle').click();await pause();assert.ok(document.querySelector('#buy-avatar-bundle').disabled);document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-profile]').click();document.querySelector('[data-avatar]').click();assert.equal(document.querySelectorAll('[data-avatar-id]').length,3);assert.ok(document.querySelector('[data-avatar-id="thunderlion"]'));console.log('PASS no promo hint, two base avatars, no upload, shop tabs and paid avatar unlock.');

document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-rank]').click();assert.match(document.querySelector('#next-dialog').textContent,/Твоё звание/);document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-nav="shop"]').click();await pause();document.querySelector('[data-shop-tab="skins"]').click();assert.equal(document.querySelectorAll('.skin-card').length,7);document.querySelector('[data-equip-skin="neon"]').click();await pause();assert.ok(document.querySelector('[data-equip-skin="neon"]').disabled);console.log('PASS avatar opens profile, separate rank dialog, skin selection persists.');
document.querySelector('[data-skin-symbol="circle"]').click();assert.equal(document.querySelectorAll('.skin-card').length,7);document.querySelector('[data-skin-symbol="powerful"]').click();assert.equal(document.querySelectorAll('.skin-card').length,7);assert.ok(document.querySelector('[data-equip-skin="storm"]'));document.querySelector('[data-equip-skin="storm"]').click();await pause();assert.ok(document.querySelector('[data-equip-skin="storm"]').disabled);assert.ok(document.querySelector('.arcana-bolts'));console.log('PASS shield skins, Arcana preview and purchase UI.');

document.querySelector('.skin-symbol-tabs').scrollLeft=520;document.querySelector('.skins-carousel').scrollLeft=760;document.querySelector('[data-equip-skin="classic"]').click();await pause();assert.equal(document.querySelector('.skin-symbol-tabs').scrollLeft,520);assert.equal(document.querySelector('.skins-carousel').scrollLeft,760);assert.equal(document.querySelector('[data-skin-symbol="powerful"]').getAttribute('aria-pressed'),'true');console.log('PASS selected booster and both scroll positions retained after equip.');
