import assert from 'node:assert/strict';import fs from 'node:fs';import {parseHTML} from 'linkedom';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {freshProgress} from '../dist/economy.mjs';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Q{constructor(s){this.s=s;this.args=[];}bind(...a){this.args=a;return this;}async first(){return sql.prepare(this.s).get(...this.args)??null;}async all(){return{results:sql.prepare(this.s).all(...this.args)};}async run(){return{meta:sql.prepare(this.s).run(...this.args)};}}
const DB={prepare:s=>new Q(s),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const p=freshProgress();p.nick='Инвентарь';p.human.unlocked.push('sword');
const {document,window}=parseHTML(fs.readFileSync('dist/index.html','utf8'));globalThis.document=document;globalThis.window=window;const create=document.createElement.bind(document);document.createElement=(tag,...args)=>{const el=create(tag,...args);if(tag==='dialog'){el.showModal=()=>el.open=true;el.close=()=>el.open=false;}return el;};
const registration=await worker.fetch(new Request('https://game.test/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nick:p.nick})}),{DB});const registered=await registration.json();sql.prepare('UPDATE profiles SET data=? WHERE id=?').run(JSON.stringify(p),registered.id);const values=new Map([['symbols-progress-v1',JSON.stringify(p)],['symbols-session',JSON.stringify({id:registered.id,token:registered.token})]]);globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};globalThis.setInterval=()=>0;globalThis.fetch=async(url,opts)=>worker.fetch(new Request('https://game.test'+url,{...opts,headers:{...opts.headers,Origin:'https://game.test'}}),{DB});const pause=()=>new Promise(r=>setTimeout(r,5));


await import('../dist/next.mjs');await pause();
document.querySelector('[data-nav="upgrades"]').click();await pause();assert.match(document.body.textContent,/110|100 жизней/);document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-nav="shop"]').click();await pause();document.querySelector('[data-shop-tab="skins"]').click();
assert.ok(document.querySelector('[data-skin-symbol="king"]'));assert.ok(document.querySelector('[data-skin-symbol="sword"]'));assert.equal(document.querySelector('[data-skin-symbol="inspect"]'),null);document.querySelector('[data-skin-symbol="king"]').click();assert.match(document.body.textContent,/Король/);console.log('PASS upgrade navigation, owned-symbol filtering and king skin preview.');
