import assert from 'node:assert/strict';import fs from 'node:fs';import {parseHTML} from 'linkedom';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';import {freshProgress} from '../dist/economy.mjs';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Q{constructor(s){this.s=s;this.args=[];}bind(...a){this.args=a;return this;}async first(){return sql.prepare(this.s).get(...this.args)??null;}async all(){return{results:sql.prepare(this.s).all(...this.args)};}async run(){return{meta:sql.prepare(this.s).run(...this.args)};}}
const DB={prepare:s=>new Q(s),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const p=freshProgress();p.nick='Инвентарь';p.human.unlocked.push('sword');
const {document,window}=parseHTML(fs.readFileSync('dist/index.html','utf8'));globalThis.document=document;globalThis.window=window;const create=document.createElement.bind(document);document.createElement=(tag,...args)=>{const el=create(tag,...args);if(tag==='dialog'){el.showModal=()=>el.open=true;el.close=()=>el.open=false;}return el;};
const registration=await worker.fetch(new Request('https://game.test/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nick:p.nick})}),{DB});const registered=await registration.json();sql.prepare('UPDATE profiles SET data=? WHERE id=?').run(JSON.stringify(p),registered.id);const values=new Map([['symbols-progress-v1',JSON.stringify(p)],['symbols-session',JSON.stringify({id:registered.id,token:registered.token})]]);globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};globalThis.setInterval=()=>0;globalThis.fetch=async(url,opts)=>worker.fetch(new Request('https://game.test'+url,{...opts,headers:{...opts.headers,Origin:'https://game.test'}}),{DB});const pause=()=>new Promise(r=>setTimeout(r,5));
await import('../dist/next.mjs');await pause();assert.ok(document.querySelector('[data-nav="inventory"]'));assert.ok(document.querySelector('[data-nav="modes"]'));assert.equal(document.querySelectorAll('.hub-main>button').length,3);
document.querySelector('[data-nav="inventory"]').click();await pause();document.querySelector('[data-item="sword"]').click();assert.match(document.querySelector('#next-dialog').textContent,/В инвентаре: 1/);document.querySelector('#sell-item').click();document.querySelector('#sell-form [name=price]').value='40';document.querySelector('#sell-form').onsubmit({preventDefault(){}});await pause();assert.ok(document.querySelector('.inventory-grid'));assert.match(document.body.textContent,/Выставлено на рынок/);document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-nav="market"]').click();await pause();document.querySelector('[data-market-symbol="sword"]').click();await pause();assert.match(document.body.textContent,/Снять с продажи/);assert.equal(document.querySelectorAll('.offer-row').length,1);assert.equal(document.querySelectorAll('.offers-symbol>svg').length,1);assert.ok(document.querySelector('#market-back'));document.querySelector('[data-cancel-listing]').click();await pause();assert.match(document.body.textContent,/Предложений пока нет/);document.querySelector('#market-back').click();await pause();
document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-promo]').click();document.querySelector('#next-dialog input').value='BOSS4229';document.querySelector('#next-dialog form').onsubmit({preventDefault(){}});await pause();let saved=JSON.parse(sql.prepare('SELECT data FROM vaults WHERE profile_id=?').get(registered.id).data);for(const t of Object.keys(saved.inventory))saved.inventory[t]=50;saved.inventory.sword=51;sql.prepare('UPDATE vaults SET data=? WHERE profile_id=?').run(JSON.stringify(saved),registered.id);document.querySelector('[data-promo]').click();document.querySelector('#next-dialog input').value='BOSS4229';document.querySelector('#next-dialog [data-close]').click();
// Re-fetch profile through a successful avatar choice.
document.querySelector('[data-avatar]').click();assert.equal(document.querySelectorAll('[data-avatar-id]').length,10);document.querySelector('[data-avatar-id="fox"]').click();await pause();assert.ok(document.querySelector('.avatar-fox'));document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-nav="inventory"]').click();await pause();assert.equal(document.querySelectorAll('[data-item="sword"]').length,1);assert.equal(document.querySelector('[data-item="sword"] .inventory-count').textContent,'×51');assert.equal(document.querySelectorAll('.inventory-card').length,15);assert.equal(document.querySelectorAll('.rarity-strip').length,15);assert.equal(document.querySelector('#more-inventory'),null);document.querySelector('[data-item="sword"]').click();assert.match(document.querySelector('#next-dialog').textContent,/В инвентаре: 51/);document.querySelector('#next-dialog [data-close]').click();document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-nav="quests"]').click();await pause();assert.equal(document.querySelectorAll('.quest-card').length,2);assert.equal(document.querySelectorAll('.quest-reward').length,2);assert.deepEqual([...document.querySelectorAll('.quest-reward')].map(e=>e.textContent.includes('+2')), [true,false]);
document.querySelector('[data-nav="home"]').click();await pause();document.querySelector('[data-nav="modes"]').click();await pause();assert.equal(document.querySelectorAll('.mode-list button').length,4);document.querySelector('[data-start="trial"]').click();await pause();assert.equal(document.querySelectorAll('.unified-board [data-index]').length,140);assert.ok(document.querySelector('[data-side="0"][data-index="56"]'));document.querySelector('[data-side="0"][data-index="56"]').click();await pause();assert.ok(document.querySelector('[data-symbol="king"]'));assert.equal(document.querySelectorAll('.frontier').length,14);
console.log('PASS v2 UI: three primary buttons, inventory quantities, sell/cancel market, promo, two one-buck quests, four modes, unified board and king placement.');
