import {hasSymbol,upgradeInfo,maxUpgrade} from '../dist/upgrades.mjs';
import {SKINS,SKIN_SYMBOLS,ownsSkin,skinsFor} from '../dist/skins.mjs';
import {syncEntitlements} from './entitlements.mjs';
import {CASES,casePrice,drawCase} from '../dist/cases.mjs';
import {unlockedFrames,activeFrame} from '../dist/frames.mjs';
import {AVATARS} from '../dist/avatars.mjs';
import {parseMoney,normalizeWallet,addMoney} from '../dist/money.mjs';
import {BASE,PRICES,freshProgress,validateProgress,mergeOnlineEarnings} from '../dist/economy.mjs';
import {TYPES} from '../dist/engine.mjs';
import {cleanNick} from '../dist/profile.mjs';
import {trialResult,levelInfo} from '../dist/progression.mjs';
import {startArena,arenaAction,arenaBotMove} from './arena-engine.mjs';
const uuid=()=>crypto.randomUUID();
const get=async(db,id)=>{const row=await db.prepare('SELECT * FROM vaults WHERE profile_id=?').bind(id).first();if(!row)return null;const d=normalizeWallet(JSON.parse(row.data));if(!d.ownedSkins)d.ownedSkins=Object.fromEntries(Object.entries(d.skins??{}).filter(([t,k])=>SKIN_SYMBOLS.includes(t)&&SKINS.some(s=>s.id===k)).map(([t,k])=>[t,[k]]));if(!['lion','eagle'].includes(d.avatar)&&!(['thunderlion','firec'].includes(d.avatar)&&d.ownedAvatars?.includes(d.avatar)))d.avatar='lion';for(const t of Object.keys(PRICES))d.inventory[t]??=0;return {...row,d};};
async function vault(db,me,b={}){let v=await get(db,me.id);if(v)return v;let old=JSON.parse(me.data);const modern=old.newEconomy;if(modern){old=freshProgress();old.nick=me.nick;}if(!modern&&b.progress){try{old=mergeOnlineEarnings(validateProgress(b.progress),old);}catch{}}const inventory=Object.fromEntries(Object.keys(PRICES).map(t=>[t,old.human?.unlocked?.includes(t)?1:0]));const d={nick:old.nick||me.nick,tutorialDone:old.tutorial?.status==='done',balance:old.human?.balance??1,inventory,xp:0,rank:old.rank??null,rankProgress:Math.min(80,(old.trial?.results?.length??0)*20),trialRun:(old.trial?.results??[]).slice(0,4),history:old.history??[],claims:old.redeemedPromos??[],m4fx:old.m4fxActivations??(old.redeemedPromos?.includes('M4FX')?1:0),instantUsed:old.instantWinsUsed??0,quests:{clean:0,blocks:0},game:null};await db.prepare('INSERT OR IGNORE INTO vaults(profile_id,data,revision) VALUES(?,?,0)').bind(me.id,JSON.stringify(d)).run();return get(db,me.id);}
// Every multi-row operation starts with a conditional receipt in the same D1 transaction.
// If any revision changed, all subsequent writes become no-ops.
async function commit(db,owner,rows,changes,extra={}){const op=uuid(),clauses=[],values=[];for(const r of rows){clauses.push('EXISTS(SELECT 1 FROM vaults WHERE profile_id=? AND revision=?)');values.push(r.profile_id,r.revision);}if(extra.game){clauses.push('EXISTS(SELECT 1 FROM arenas WHERE id=? AND revision=?)');values.push(extra.game.id,extra.game.revision);}if(extra.listing){clauses.push("EXISTS(SELECT 1 FROM listings WHERE id=? AND status='open')");values.push(extra.listing.id);}const guard='EXISTS(SELECT 1 FROM operations WHERE id=?)';const statements=[db.prepare(`INSERT INTO operations(id,owner,created) SELECT ?,?,? WHERE ${clauses.join(' AND ')||'1'}`).bind(op,owner,Date.now(),...values)];for(const r of rows)statements.push(db.prepare(`UPDATE vaults SET data=?,revision=revision+1 WHERE profile_id=? AND ${guard}`).bind(JSON.stringify(r.d),r.profile_id,op));for(const c of changes)statements.push(db.prepare(c.sql.replaceAll('$GUARD',guard)).bind(...c.args,op));await db.batch(statements);if(!await db.prepare('SELECT id FROM operations WHERE id=?').bind(op).first())throw Error('Данные изменились. Обнови экран и повтори действие.');}
const gameRow=async(db,id)=>id?db.prepare('SELECT * FROM arenas WHERE id=?').bind(id).first():null;
function member(v){return {id:v.profile_id,nick:v.d.nick,avatar:v.d.avatar??'lion',frame:activeFrame(v.d),level:levelInfo(v.d.xp).level,rank:v.d.rank,skins:v.d.skins??{},upgrades:v.d.upgrades??{},inventory:{...v.d.inventory},bot:false};}
function gameUpdate(r,s){return {sql:'UPDATE arenas SET data=?,status=?,revision=revision+1,updated=? WHERE id=? AND $GUARD',args:[JSON.stringify(s),s.status,Date.now(),r.id]};}
async function users(db,s){const out=[];for(const p of s.players)if(!p.bot&&!out.some(v=>v.profile_id===p.id))out.push(await get(db,p.id));return out;}
function finish(s,vs,now,method='normal'){if(s.awarded)return;s.awarded=true;const elapsed=s.started===null?0:now-s.started;s.results={};for(let seat=0;seat<s.players.length;seat++){const p=s.players[seat];if(p.bot||s.mode==='local'&&seat>0)continue;const v=vs.find(v=>v.profile_id===p.id),d=v.d,won=s.g.winner===seat%2;const eligible=method==='normal'&&s.started!==null&&s.mode!=='local';const q=[];if(eligible&&won&&s.damage[seat]===0&&(s.mode!=='trial'?s.level>=2||s.players.some(p=>!p.bot&&p.id!==v.profile_id):s.level>=2)){addMoney(d,200);d.quests.clean++;q.push('clean');}if(eligible&&s.blocks[seat]>=3){addMoney(d,100);d.quests.blocks++;q.push('blocks');}let xp=eligible?(won?100:25)+q.length*50:0;if(eligible&&['duel','room'].includes(s.mode)&&won&&!s.damage[seat]&&elapsed<=15000)xp=1200;if(method==='promo'&&won&&p.id===s.instantWinner)xp=1000;d.xp+=xp;syncEntitlements(d);if(s.tutorial)d.tutorialDone=true;let rank=null;if(s.mode==='trial')rank=trialResult(d,won,s.damage[seat],elapsed);const record={id:s.id,at:now,mode:s.mode,level:s.level,opponent:s.players.filter((_,i)=>i%2!==seat%2).map(p=>p.nick).join(', '),outcome:won?'win':'loss',elapsed,damage:s.damage[seat],xp,quests:q,method};d.history=[record,...d.history.filter(r=>r.id!==s.id)].slice(0,100);s.results[p.id]={won,xp,quests:q,rank,elapsed,level:levelInfo(d.xp),bucks:q.reduce((n,id)=>n+(id==='clean'?2:1),0)};}}
async function tick(db,row,now){let s=JSON.parse(row.data);if(s.status==='done')return row;const vs=await users(db,s);let changed=false;
 if(s.status==='waiting'&&s.deadline!==null&&now>=s.deadline){while(s.players.length<s.capacity)s.players.push({id:'bot-'+uuid(),nick:'Бот '+(s.players.length+1),bot:true,inventory:{}});startArena(s,now);changed=true;}
 if(['setup','play'].includes(s.status)){
  const actor=s.players[s.actor];if(actor.bot&&now-s.turnAt>=450){try{arenaAction(s,arenaBotMove(s),s.actor,now);}catch{const g=s.g,p=s.actor%2;let i=g.boards[p].findIndex(t=>!t);if(i>=0)arenaAction(s,{type:'smile',index:i},s.actor,now);else{s.g.winner=1-p;s.status='done';s.finished=now;}}changed=true;}
  else if(!actor.bot&&now-s.turnAt>90000){s.g.winner=1-s.actor%2;s.status='done';s.finished=now;s.reason='Время на ход вышло';changed=true;}
 }
 if(changed){if(s.status==='done')finish(s,vs,now,s.reason?'timeout':'normal');await commit(db,'tick',vs,[gameUpdate(row,s)],{game:row});row=await gameRow(db,row.id);}return row;}
export async function v2(db,me,route,b,now){let v=await vault(db,me,b);if(syncEntitlements(v.d)){await commit(db,me.id,[v],[]);v=await get(db,me.id);}const response=async(extra={})=>({profile:(await get(db,me.id)).d,...extra});
 if(route==='profile')return response();
 if(route==='upgrade'){if(b.symbol!=='king'&&!TYPES[b.symbol])throw Error('Неизвестный символ');if(!hasSymbol(v.d,b.symbol))throw Error('Сначала получи этот символ');const info=upgradeInfo(v.d,b.symbol);if(info.price===null)throw Error(info.unlimited?'У этого символа уже нет лимита':'Максимальное улучшение');if(b.level!==info.level)throw Error('Улучшение уже изменилось. Обнови экран');if(v.d.balanceCents<info.price*100)throw Error('Не хватает рубинов');const purchase=b.max===true?maxUpgrade(v.d,b.symbol):{count:1,cost:info.price*100};addMoney(v.d,-purchase.cost);v.d.upgrades??={};v.d.upgrades[b.symbol]=info.level+purchase.count;await commit(db,me.id,[v],[]);return response();}
 if(route==='frame'){if(b.frame!==null&&(!Number.isInteger(b.frame)||b.frame<1||b.frame>unlockedFrames(v.d.xp)))throw Error('Эта рамка пока не открыта');v.d.frame=b.frame;await commit(db,me.id,[v],[]);return response();}
 if(route==='buy-case'||route==='open-case'){const c=CASES.find(c=>c.id===b.case);if(!c)throw Error('Кейс не найден');const key=String(b.key??'');if(!/^[a-f0-9-]{36}$/.test(key))throw Error('Повтори действие');v.d.caseReceipts??=[];const receipt=v.d.caseReceipts.find(r=>r.key===key);if(receipt){if(receipt.route!==route||receipt.case!==c.id)throw Error('Повтори действие');return response({drop:receipt.drop??null});}v.d.cases??={};let drop=null;if(route==='buy-case'){if(v.d.balanceCents<casePrice(c))throw Error('Не хватает рубинов');addMoney(v.d,-casePrice(c));v.d.cases[c.id]=(v.d.cases[c.id]??0)+1;}else{if(!(v.d.cases[c.id]>0))throw Error('Сначала купи кейс');drop=drawCase(c);v.d.cases[c.id]--;v.d.inventory[drop]=(v.d.inventory[drop]??0)+1;v.d.lastCaseDrop={symbol:drop,case:c.id,at:now};}v.d.caseReceipts.push({key,route,case:c.id,drop});v.d.caseReceipts=v.d.caseReceipts.slice(-100);await commit(db,me.id,[v],[]);return response({drop});}
 if(route==='skin'||route==='buy-skin'){const skin=skinsFor(b.symbol).find(s=>s.id===b.skin);if(!hasSymbol(v.d,b.symbol))throw Error('Сначала получи этот символ');if(!SKIN_SYMBOLS.includes(b.symbol)||!skin)throw Error('Расцветка недоступна');if(!ownsSkin(v.d,b.symbol,b.skin)){if(route!=='buy-skin')throw Error('Сначала купи скин');if(v.d.balanceCents<skin.price*100)throw Error('Не хватает рубинов');addMoney(v.d,-skin.price*100);v.d.ownedSkins[b.symbol]??=[];v.d.ownedSkins[b.symbol].push(b.skin);}v.d.skins??={};v.d.skins[b.symbol]=b.skin;await commit(db,me.id,[v],[]);return response();}
 if(route==='nickname'){v.d.nick=cleanNick(b.nick);await commit(db,me.id,[v],[]);return response();}
 if(route==='avatar'){if(!['lion','eagle'].includes(b.avatar)&&!(['thunderlion','firec'].includes(b.avatar)&&v.d.ownedAvatars?.includes(b.avatar)))throw Error('Эта аватарка недоступна');v.d.avatar=b.avatar;await commit(db,me.id,[v],[]);return response();}
 if(route==='buy-avatar'){const offers={thunderlion:{price:50000,symbol:'arrowx2',quantity:5},firec:{price:100000,symbol:'inspect',quantity:1}},offer=Object.hasOwn(offers,b.avatar)?offers[b.avatar]:null;if(!offer)throw Error('Товар не найден');if(v.d.ownedAvatars?.includes(b.avatar))return response();if(v.d.balanceCents<offer.price)throw Error('Не хватает рубинов');addMoney(v.d,-offer.price);v.d.ownedAvatars??=[];v.d.ownedAvatars.push(b.avatar);v.d.inventory[offer.symbol]=(v.d.inventory[offer.symbol]??0)+offer.quantity;v.d.avatar=b.avatar;await commit(db,me.id,[v],[]);return response();}
 if(route==='instant'&&!v.d.claims.includes('M4FX5267'))throw Error('Быстрая победа недоступна');
 if(route==='promo')throw Error('Промокод не действует');
 if(route==='market'){const order=b.desc?'DESC':'ASC',type=b.symbol&&Object.hasOwn(PRICES,b.symbol)?b.symbol:null;const offset=Number.isSafeInteger(b.offset)&&b.offset>=0?b.offset:0;const result=await db.prepare(`SELECT l.id,l.seller,l.symbol,l.skin,l.price,COALESCE(l.price_cents,l.price*100) AS priceCents,l.created,json_extract(v.data,'$.nick') AS nick FROM listings l JOIN vaults v ON v.profile_id=l.seller WHERE l.status='open' ${type?'AND l.symbol=?':''} ORDER BY COALESCE(l.price_cents,l.price*100) ${order},l.created,l.id LIMIT 61 OFFSET ?`).bind(...(type?[type]:[]),offset).all();const groups=await db.prepare(`SELECT symbol,COUNT(*) AS count,MIN(COALESCE(price_cents,price*100)) AS minPrice,MAX(COALESCE(price_cents,price*100)) AS maxPrice FROM listings WHERE status='open' GROUP BY symbol ORDER BY ${b.desc?'maxPrice DESC':'minPrice ASC'}`).all();return response({listings:result.results.slice(0,60),groups:groups.results,nextOffset:result.results.length>60?offset+60:null});}
 if(route==='sell'){const t=b.symbol,skin=b.skin&&b.skin!=='classic'?skinsFor(t).find(s=>s.id===b.skin):null;if(b.skin&&b.skin!=='classic'&&!skin)throw Error('Скин не найден');const priceCents=parseMoney(b.price)+(skin?skin.price*90:0),price=priceCents/100;if(!Number.isSafeInteger(priceCents))throw Error('Цена вне точного числового диапазона');if(!Object.hasOwn(PRICES,t))throw Error('Неизвестный символ');if(v.d.game){const r=await gameRow(db,v.d.game);if(r&&r.status!=='done')throw Error('Сначала заверши партию');}if(!(v.d.inventory[t]>0))throw Error('Нет свободного экземпляра');const quantity=b.quantity??1;if(!Number.isSafeInteger(quantity)||quantity<1||quantity>v.d.inventory[t])throw Error('Выбери количество от 1 до '+v.d.inventory[t]);if(skin){if(quantity!==1)throw Error('Со скином продаётся один экземпляр');const owned=v.d.ownedSkins?.[t]??[],index=owned.indexOf(skin.id);if(index<0)throw Error('Этот скин тебе не принадлежит');owned.splice(index,1);if(v.d.skins?.[t]===skin.id&&!owned.includes(skin.id))v.d.skins[t]='classic';}v.d.inventory[t]-=quantity;await commit(db,me.id,[v],[{sql:"INSERT INTO listings(id,seller,symbol,price,price_cents,skin,status,created) WITH RECURSIVE copies(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM copies WHERE n<?) SELECT lower(hex(randomblob(16))),?,?,?,?,?,'open',? FROM copies WHERE $GUARD",args:[quantity,me.id,t,price,priceCents,skin?.id??null,now]}]);return response();}
 if(route==='buy'||route==='cancel'){const l=await db.prepare("SELECT * FROM listings WHERE id=? AND status='open'").bind(String(b.id)).first();if(!l)throw Error('Предложение уже недоступно');if(route==='cancel'){if(l.seller!==me.id)throw Error('Это не твоё предложение');v.d.inventory[l.symbol]++;if(l.skin){v.d.ownedSkins[l.symbol]??=[];v.d.ownedSkins[l.symbol].push(l.skin);v.d.skins??={};v.d.skins[l.symbol]=l.skin;}await commit(db,me.id,[v],[{sql:"UPDATE listings SET status='cancelled' WHERE id=? AND $GUARD",args:[l.id]}],{listing:l});}else{if(l.seller===me.id)throw Error('Это твой предмет');const cents=l.price_cents??l.price*100;if(v.d.balanceCents<cents)throw Error('Не хватает рубинов');const seller=await get(db,l.seller);if(!Number.isSafeInteger(seller.d.balanceCents+cents))throw Error('Цена превышает допустимый баланс');addMoney(v.d,-cents);v.d.inventory[l.symbol]++;if(l.skin){v.d.ownedSkins[l.symbol]??=[];v.d.ownedSkins[l.symbol].push(l.skin);v.d.skins??={};v.d.skins[l.symbol]=l.skin;}addMoney(seller.d,cents);await commit(db,me.id,[v,seller],[{sql:"UPDATE listings SET status='sold',buyer=? WHERE id=? AND $GUARD",args:[me.id,l.id]}],{listing:l});}return response();}
 if(route==='start'){
  if(v.d.game){const old=await gameRow(db,v.d.game);if(old&&old.status!=='done')return response({game:JSON.parse(old.data),revision:old.revision});}
  const mode=['play','duel','team','trial','local','room'].includes(b.mode)?b.mode:'play',size=b.small?[10,14]:[28,20];const capacity=mode==='team'?4:2;
  if(mode==='room'&&b.code){const code=String(b.code).trim().toUpperCase();const row=await db.prepare("SELECT * FROM arenas WHERE mode='room' AND status='waiting' AND json_extract(data,'$.code')=?").bind(code).first();if(!row)throw Error('Комната не найдена');const s=JSON.parse(row.data);if(s.players.some(p=>p.id===me.id))throw Error('Ты уже в этой комнате');s.players.push(member(v));v.d.game=s.id;startArena(s,now);await commit(db,me.id,[v],[gameUpdate(row,s)],{game:row});return response({game:s,revision:row.revision+1});}
  if(!['trial','local','room'].includes(mode)&&!(mode==='play'&&!v.d.tutorialDone)){
   const wait=await db.prepare("SELECT * FROM arenas WHERE mode=? AND status='waiting' ORDER BY updated LIMIT 1").bind(mode).first();if(wait){let s=JSON.parse(wait.data);if(s.players.length<capacity&&now<s.deadline&&!s.players.some(p=>p.id===me.id)){s.players.push(member(v));v.d.game=s.id;if(s.players.length===capacity)startArena(s,now);await commit(db,me.id,[v],[gameUpdate(wait,s)],{game:wait});return response({game:s,revision:wait.revision+1});}}
  }
  const id=uuid(),s={id,mode,size,capacity,players:[member(v)],status:'waiting',created:now,deadline:mode==='room'?null:now+8000,code:mode==='room'?uuid().replaceAll('-','').slice(0,6).toUpperCase():null,tutorial:mode==='play'&&!v.d.tutorialDone,level:mode==='trial'?(v.d.trialRun?.length??0):2,events:[],started:null};v.d.game=id;
  if(mode==='play'&&!v.d.tutorialDone){s.level=0;s.players.push({id:'bot-'+uuid(),nick:'Очень лёгкий бот',bot:true,inventory:{}});startArena(s,now);}
  if(mode==='trial'){s.players.push({id:'bot-'+uuid(),nick:'Бот · испытание',bot:true,inventory:{}});startArena(s,now);}if(mode==='local'){s.players.push({...member(v),id:me.id,nick:'Игрок 2'});startArena(s,now);}
  await commit(db,me.id,[v],[{sql:'INSERT INTO arenas(id,mode,status,data,revision,updated) SELECT ?,?,?,?,0,? WHERE $GUARD',args:[id,mode,s.status,JSON.stringify(s),now]}]);return response({game:s,revision:0});
 }
 if(['poll','action','leave','instant'].includes(route)){
  let row=await gameRow(db,v.d.game);if(!row)return response({game:null});if(!['action','instant'].includes(route))row=await tick(db,row,now);let s=JSON.parse(row.data);const seat=s.players.findIndex(p=>p.id===me.id);if(seat<0)throw Error('Партия недоступна');
  if(route==='poll')return response({game:s,revision:row.revision});
  if(row.status==='done')return response({game:s,revision:row.revision});
  if(b.revision!==undefined&&b.revision!==row.revision)return response({game:s,revision:row.revision});
  const vs=await users(db,s);v=vs.find(v=>v.profile_id===me.id);
  let method='normal';
  if(route==='leave'){if(s.status==='waiting'){s.players=s.players.filter(p=>p.id!==me.id);v.d.game=null;if(!s.players.length)s.status='done';}else{s.g.winner=1-seat%2;s.status='done';s.finished=now;method='leave';}}
  else if(route==='instant'){if(!v.d.claims.includes('M4FX5267')||s.mode==='local')throw Error('Быстрая победа недоступна');if(!s.g)throw Error('Дождись начала');s.instantWinner=me.id;s.g.winner=seat%2;s.status='done';s.finished=now;method='promo';}
  else{const actor=s.mode==='local'?s.actor:seat;const t=b.action?.type;if(t in PRICES&&!(v.d.inventory[t]>0)&&!s.usedSymbols?.[actor]?.[t])throw Error('Этот символ закончился');const result=arenaAction(s,b.action,actor,now);if(result.consumed){v.d.inventory[result.consumed]--;if(s.mode==='local')s.players.forEach(p=>p.inventory={...v.d.inventory});}}
  if(s.status==='done'&&s.g)finish(s,vs,now,method);await commit(db,me.id,vs,[gameUpdate(row,s)],{game:row});return response({game:s,revision:row.revision+1});
 }
 throw Error('Неизвестное действие');
}
