import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),nick:text('nick').notNull(),data:text('data').notNull(),seen:integer('seen').notNull(),matchId:text('match_id'),lastOpponent:text('last_opponent')},t=>[uniqueIndex('profiles_token').on(t.tokenHash),index('profiles_seen').on(t.seen)]);
export const matches=sqliteTable('matches',{id:text('id').primaryKey(),code:text('code'),kind:text('kind').notNull(),status:text('status').notNull(),p0:text('p0').notNull(),p1:text('p1'),revision:integer('revision').notNull().default(0),state:text('state').notNull(),updated:integer('updated').notNull()},t=>[uniqueIndex('matches_code').on(t.code),index('matches_waiting').on(t.kind,t.status,t.updated)]);
export const recovery=sqliteTable('recovery',{profileId:text('profile_id').primaryKey(),codeHash:text('code_hash').notNull()},t=>[uniqueIndex('recovery_code').on(t.codeHash)]);
export const recoveryLimits=sqliteTable('recovery_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const vaults=sqliteTable('vaults',{profileId:text('profile_id').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull().default(0)});
export const listings=sqliteTable('listings',{id:text('id').primaryKey(),seller:text('seller').notNull(),symbol:text('symbol').notNull(),price:integer('price').notNull(),priceCents:integer('price_cents'),skin:text('skin'),status:text('status').notNull(),buyer:text('buyer'),created:integer('created').notNull()},t=>[index('listings_market').on(t.status,t.symbol,t.price),index('listings_seller').on(t.seller,t.status)]);
export const arenas=sqliteTable('arenas',{id:text('id').primaryKey(),mode:text('mode').notNull(),status:text('status').notNull(),data:text('data').notNull(),revision:integer('revision').notNull().default(0),updated:integer('updated').notNull()},t=>[index('arenas_queue').on(t.status,t.mode,t.updated)]);
export const operations=sqliteTable('operations',{id:text('id').primaryKey(),owner:text('owner').notNull(),created:integer('created').notNull()});

export const accountSessions=sqliteTable('account_sessions',{tokenHash:text('token_hash').primaryKey(),profileId:text('profile_id').notNull(),created:integer('created').notNull()},t=>[index('account_sessions_profile').on(t.profileId)]);
