import {mergeHistory} from './history.mjs';
export const PRICES={arrowx2:100,circle:20,inspect:120,powerful:150,angry:150,feedback:156,laser:170,tank:200,teleport:200,sword:750,electricity:75};
export const BASE=['arrow','smile','point','erase'];
export const QUESTS=[{id:'breach',title:'Разрушить щит',text:'Уничтожь круг противника в игре с ботом. За каждый круг — 1 бакс.',reward:1},{id:'arrow',title:'Точный выстрел',text:'Попади стрелочкой во вражеского короля.',reward:5},{id:'smile',title:'Пробить защиту',text:'Уничтожь вражеский смайлик.',reward:10},{id:'streak',title:'Пять побед подряд',text:'Победи бота 5 раз подряд. Можно на одной сложности. Поражение сбрасывает серию.',reward:50}];
export const STORAGE_KEY='symbols-progress-v1';
const wallet=(balance)=>({balance,unlocked:[...BASE],streak:0,counts:{arrow:0,smile:0,streak:0,breach:0}});
export function freshProgress(){return {version:1,tutorial:{status:'new'},history:[],nick:'',rank:null,trial:null,human:wallet(1),bot:wallet(0),processed:[]};}
export function validateProgress(value){if(value?.instantWinsUsed!==undefined&&(!Number.isInteger(value.instantWinsUsed)||value.instantWinsUsed<0||value.instantWinsUsed>25))throw Error('Повреждено сохранение');if(value?.version!==1)throw Error('Не удалось прочитать сохранение');for(const who of ['human','bot']){const w=value[who];if(w?.counts&&w.counts.breach===undefined)w.counts.breach=0;if(!w||!Number.isSafeInteger(w.balance)||w.balance<0||!Array.isArray(w.unlocked)||w.unlocked.some(t=>!BASE.includes(t)&&!(t in PRICES))||BASE.some(t=>!w.unlocked.includes(t))||!Number.isInteger(w.streak)||w.streak<0||w.streak>4||!w.counts||Object.keys(w.counts).some(t=>!['arrow','smile','streak','breach'].includes(t))||['arrow','smile','streak','breach'].some(t=>!Number.isSafeInteger(w.counts[t])||w.counts[t]<0))throw Error('Повреждено сохранение');}if(value.redeemedPromos!==undefined&&(!Array.isArray(value.redeemedPromos)||value.redeemedPromos.some(c=>typeof c!=='string')))throw Error('Повреждено сохранение');if(!Array.isArray(value.processed))throw Error('Повреждено сохранение');return value;}
export function purchase(progress,type,who='human'){const w=progress[who],price=PRICES[type];if(!w||price===undefined)throw Error('Этот символ не продаётся');if(w.unlocked.includes(type))throw Error('Символ уже открыт');if(w.balance<price)throw Error('Не хватает баксов');w.balance-=price;w.unlocked.push(type);return price;}
export function botShopping(progress){const bought=[];for(const [type,price] of Object.entries(PRICES))if(!progress.bot.unlocked.includes(type)&&progress.bot.balance>=price){purchase(progress,type,'bot');bought.push(type);}return bought;}
export function settle(progress,{id,mode,events=[],winner=null}){
 if(progress.processed.includes(id))return [];
 const paid=[],credit=(owner,quest)=>{const who=mode==='bot'&&owner===1?'bot':'human',w=progress[who],q=QUESTS.find(q=>q.id===quest);w.balance+=q.reward;w.counts[quest]=(w.counts[quest]??0)+1;paid.push({who,amount:q.reward,quest});};
 for(const event of events)for(const reward of event.rewards??[])if((['arrow','smile'].includes(reward.quest)||mode==='bot'&&reward.quest==='breach')&&[0,1].includes(reward.owner))credit(reward.owner,reward.quest);
 if(mode==='bot'&&[0,1].includes(winner)){const who=winner===0?'human':'bot',other=winner===0?'bot':'human';progress[other].streak=0;if(++progress[who].streak===5){credit(winner,'streak');progress[who].streak=0;}}
 progress.processed.push(id);if(progress.processed.length>512)progress.processed.shift();return paid;
}
// Merge only server-earned online rewards that this browser has not received yet.
export function mergeOnlineEarnings(local,remote){for(const q of ['arrow','smile']){const current=local.onlineCounts?.[q]??0,next=remote.onlineCounts?.[q]??0,delta=Math.max(0,next-current);if(delta){local.human.balance+=delta*(q==='arrow'?5:10);local.human.counts[q]+=delta;}local.onlineCounts??={};local.onlineCounts[q]=Math.max(current,next);}for(const code of remote.redeemedPromos??[]){if(Object.hasOwn(PROMOS,code)&&!(local.redeemedPromos??[]).includes(code)){local.redeemedPromos??=[];local.redeemedPromos.push(code);local.human.balance+=PROMOS[code];}}local.m4fxActivations=Math.max(local.m4fxActivations??(local.redeemedPromos?.includes('M4FX')?1:0),remote.m4fxActivations??(remote.redeemedPromos?.includes('M4FX')?1:0));local.instantWinsUsed=Math.max(local.instantWinsUsed??0,remote.instantWinsUsed??0);local.history=mergeHistory(local.history,remote.history);return local;}

const PROMOS={BOSS4229:50,'10000B':10000};
export function redeemPromo(progress,input){const code=String(input).replace(/\s/g,'').toUpperCase();if(code==='M4FX5267')throw Error('Этот промокод больше не действует.');if(!Object.hasOwn(PROMOS,code))throw Error('Такого промокода нет. Проверь написание.');progress.redeemedPromos??=[];if(code==='M4FX'){const count=progress.m4fxActivations??(progress.redeemedPromos.includes(code)?1:0);if(count>=5)throw Error('Этот промокод уже активирован 5 раз.');progress.m4fxActivations=count+1;}else if(progress.redeemedPromos.includes(code))throw Error('Ты уже использовал этот промокод.');progress.human.balance+=PROMOS[code];if(!progress.redeemedPromos.includes(code))progress.redeemedPromos.push(code);return PROMOS[code];}

export function instantWinsLeft(progress){return 0;}
export function useInstantWin(progress,game,mode,trial){if(mode!=='bot'||trial&&instantWinsLeft(progress)!==Infinity||!game||game.winner!==null||!instantWinsLeft(progress))throw Error('Быстрая победа недоступна');if(instantWinsLeft(progress)!==Infinity)progress.instantWinsUsed=(progress.instantWinsUsed??0)+1;game.winner=0;game.pending=[];}
